### ISSUE TITLE
Statistics are not displayed, and there is no talent selection (duplicate Issue )

### ISSUE THREAD

**Issue by AestroFidelium** [jamiephan/HeroesOfTheStorm_TryMode2.0#14]
However, when trying to sort it, it works properly
The same applies to talents if they are issued through addtalent they will work

![image](https://user-images.githubusercontent.com/56913791/132617641-878f3c7f-a160-4262-b9cb-318e98f05a54.png)

_I'm sorry for posting the Issue for the second time
I'm doing this for the first time_

**Comment by jamiephan** [comment]
This happens for every custom map when the `.stormmap` file was load directly (e.g double click to open or via command line).

The only way to fix it is to replace the in game try mode, or tutorial modes with the custom map (or this case, the try mode 2.0 map)

For more details on how to replace it, you can have a look here: https://jamiephan.github.io/HeroesOfTheStorm_TryMode2.0/install.html#runStormmap-customstormmap
