### ISSUE TITLE
Hi. i have downloaded the release map.but do i have to login to get in the game?is this offline?

### ISSUE THREAD

**Issue by BlackBoar101** [jamiephan/HeroesOfTheStorm_TryMode2.0#20]
If it just a offline map , can we skip the login process? 
like Dota2 the offline single mode. it will be much more convient to try those maps.
like some newbe the dont have a blizzard account they can enjoy the map and later may join the mod community.

**Comment by BlackBoar101** [comment]
hots was official announced dead this week. lets modders enlength the life of hots. 
playing a modder`s single game requiring login is truely a nonsense. 
like diablo 3. this is the shit cause blizzard death.

**Comment by Cruglk** [comment]
If you can somehow run a mod to play with someone - that's when the game comes to life. Even taking into account the fact that you will have to create maps in the XML editor, if we can play the created maps with someone over the network, then this will be enough for the development of the game. Unfortunately, I personally did not see a solution for anyone to be able to run the HotS mod for playing in co-op. There is only a reverse mod for SC2, where files from HotS are transferred.

**Comment by BlackBoar101** [comment]
@Cruglk My point is just let the game skip the login process first, its a great barrier for new gamers get in the game.
Hots have awsome model , animation, particles. sound and so on. some of these are much better than lol & dota2 .But it ask a player more than ten steps to get an account and update client , solves some ridiculous bugs then get in the game.

why just make it into **one step**? just download a client then play a map. a tower defence or a just fight a squence of foes to win map. even its just a solo game it helps more players get in the game. i dont ask co-op now, maybe its hard as you said at present. more players do generate more things!
 
Skip the login, maybe create a simple server just identify a fake user to get in a single map.

maybe co-op will be on the way when there are enough players.

maybe a editor will be created for hots by some golden coder later..

**Comment by BlackBoar101** [comment]
@Cruglk thank you for your map link. i will try it later.
i do agree playing with someone will be much more fun than playing along.and it the core gameplay in moba or some mod maps or like you said MMOs

But. if the Task of getting in game with out login is not hard and time consuming. i strongly advice get it done sooner or later.
Playing along is not my goal. if hots can run with out a login, it means any web any version any player who have a client can throw hots to any potential players.  they do advertisement for hots for free. and player can get in game in just one step. they can also play alone or they can create their own map and they can up load their work in mod community share with others. it helps hots community build, this is what i mean. some single play game like darksouls or elder ring or dmc or resident evil they are hard core single play game. but player doing mod happily every day~~

FOR NOW this tight link with battlenet kills mods for games like hots or diablo3 or sc2. and later diablo4. Dota really break blizzard confidence. you may say no. sc2 have a lot of mods. i will say if sc2 have the form of war3 their will be much more mods.
it is something like a football playground have only one small entrance, few people can get in. for the ousiders they may even cant see the entrance at all.

Get more players for hots. more players generate more things, good or bad. among them anything can happen.

**Comment by BlackBoar101** [comment]
@Cruglk you me we two are dicussing this lonely~~~
if hots have a much lager community , have a web on nexusmods. there will be hunderds of people discussing how to solve existing problems.

**Comment by BlackBoar101** [comment]
@Cruglk i can see get hots without login is not hard for you.
if we have the single play client. in one week time there will be 100 websites provide hots download worldwide . may be 1000 websites in one month. these are all entrances to the playground.
now there is only one, and you have to keep connect it....

**Comment by Cruglk** [comment]
@BlackBoar101 In my opinion, you clearly overestimate community involvement. In recent years less than a dozen people have been willing to understand the game code.

How old is Try Mode and how many interesting maps have we received? Two unfinished maps for the entire GitHub:
- https://github.com/Kurumi-Stella/Heroes-of-the-storm-random-maps
- https://github.com/spazzo966/HogRacing
- Several videos on YouTube related to mods. As examples of my work:
- https://www.youtube.com/watch?v=RWmswlkrwzg
- https://www.youtube.com/playlist?list=PLFKuLCzia-Rq3YBOwGX3PxtRKWCw-CNTf

And that's all. 

From the fact that now we will launch custom map in single mode no one will go to sit in the HotS code. But if it becomes possible to play the created maps with someone, I will personally create a dozen new maps, like tower defense and others.

There was an idea to create a single map and record a video as I go into it but I feel that I will lose too much time on this and there will be a minimum of interest. But if someone can create it I will gladly make posts about such a map everywhere (reddit, YouTube).

**Comment by Cruglk** [comment]
@BlackBoar101 Sorry, I only focused on the experience of playing and viewing information in the European region. If the game is so popular, then it remains to be hoped that someone will be able to do it.

**Comment by BlackBoar101** [comment]
@Cruglk man, you finally get what i mean. hots situation now is not because so many code dead process like you said. wow emulator sever starts from nothing but now it remains updating in github like cmangos and so on. because there are enough people. some knows tech stuff, some  have money, some are doing business, most are players.

you guys are still working under battlenet frame. i said this thing is a big shit. this shit`s main job is lock people onto blizzard.
few people like it.

maybe one day a goden coder can do a emulator for hots, but he must have enough supporters.

**Comment by Cruglk** [comment]
Look towards "Blizzless" - it is possible that they will be able to take on HotS.

**Comment by Cruglk** [comment]
@BlackBoar101 Look towards "Blizzless" - it is possible that they will be able to take on HotS.

**Comment by BlackBoar101** [comment]
@Cruglk hope so.
