### ISSUE TITLE
Main Images removed

### ISSUE THREAD

**Issue by Cruglk** [jamiephan/HeroesOfTheStorm_TryMode2.0#30]
Images with a flying tank on the [main page](https://jamiephan.net/HeroesOfTheStorm_TryMode2.0/) are no longer displayed: https://thumbs.gfycat.com/AntiqueFrighteningComet-size_restricted.gif [gfycat closed]

**Comment by jamiephan** [comment]
Fixed in [1484a70](https://github.com/jamiephan/HeroesOfTheStorm_TryMode2.0/commit/1484a70b71005360ecbe7ddb99fb7ddd71502e9c). Thanks for the report
